---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: CDIF XAS metadata profile
description: >-
  CDIF XAS profile for X-ray Absorption Spectroscopy datasets. Composes
  cdifCore with discovery properties and XAS-specific constraints.
allOf:
- $ref: ../../../profiles/cdifProfile/cdifCore/schema.yaml
- $ref: ../../../profiles/cdifProfile/cdifDiscovery/schema.yaml
- $ref: ../../../profiles/cdifProfile/cdifDataDescription/schema.yaml
- $ref: ../../../xasProperties/xasOptional/schema.yaml
- $ref: ../../../xasProperties/xasCore/schema.yaml

