@startuml
title AbstractGeometry
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

abstract class "AbstractGeometry" as AbstractGeometry #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "GeoCoordinates" as GeoCoordinates #D5F5E3
AbstractGeometry <|-- GeoCoordinates
class "GeoShape" as GeoShape #D5F5E3
AbstractGeometry <|-- GeoShape
class "SpatialExtent" as SpatialExtent #EEEEEE
SpatialExtent *-- "0..1" AbstractGeometry : geo
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
AbstractGeometry ..> XsdAnyUri : identifier

@enduml