@startuml
title IdentifierComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "IdentifierComponent" as IdentifierComponent #FEFECE
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- IdentifierComponent
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" IdentifierComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure *-- "1" IdentifierComponent : hasComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "0..*" IdentifierComponent : hasComponent

@enduml