@startuml
title UnitType
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "UnitType" as UnitType #FEFECE {
  +descriptiveText : string [1]
  +definition : string [1]
  +displayLabel : string [1..*]
  +externalDefinition : Reference [1]
  +identifier : Identifier [1]
  +name : string [1..*]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable --> "0..1" UnitType : measures
class "Reference" as Reference #EEEEEE
UnitType --> "1" Reference : externalDefinition
class "Identifier" as Identifier #EEEEEE
UnitType --> "1" Identifier : identifier

@enduml