@startuml
title DefinedTerm
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "DefinedTerm" as DefinedTerm #FEFECE {
  +identifier : Identifier [0..1]
  +name : string [1]
  +termCode : string [0..1]
  +inDefinedTermSet : XsdAnyUri [0..1]
  +additionalType : XsdAnyUri [0..*]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" DefinedTerm : keywords
Dataset --> "0..*" DefinedTerm : measurementTechnique
class "VariableMeasured" as VariableMeasured #EEEEEE
VariableMeasured --> "0..1" DefinedTerm : measurementTechnique
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable --> "0..1" DefinedTerm : hasIntendedDataType
InstanceVariable --> "0..*" DefinedTerm : source
InstanceVariable --> "0..*" DefinedTerm : measurementTechnique
class "Identifier" as Identifier #EEEEEE
DefinedTerm --> "0..1" Identifier : identifier
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DefinedTerm ..> XsdAnyUri : inDefinedTermSet

@enduml