@startuml
title SubstantiveValueDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "SubstantiveValueDomain" as SubstantiveValueDomain #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable --> "0..1" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "ValueAndConceptDescription" as ValueAndConceptDescription #EEEEEE
SubstantiveValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
class "EnumerationDomain" as EnumerationDomain #EEEEEE
SubstantiveValueDomain --> "0..1" EnumerationDomain : takesValuesFrom
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable --> "0..1" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
SubstantiveValueDomain ..> XsdAnyUri : identifier

@enduml