@startuml
title VariableDescriptorComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "VariableDescriptorComponent" as VariableDescriptorComponent #FEFECE {
  +type : string [1..*]
}
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" VariableDescriptorComponent : hasComponent
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure *-- "1" VariableDescriptorComponent : hasComponent
class "DescriptorVariable" as DescriptorVariable #EEEEEE
VariableDescriptorComponent --> "1" DescriptorVariable : isDefinedBy
class "VariableValueComponent" as VariableValueComponent #EEEEEE
VariableDescriptorComponent --> "1" VariableValueComponent : refersTo

@enduml