@startuml
title Geometry
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Geometry" as Geometry #FEFECE {
  +asWKT : string [0..1]
  +crs : XsdAnyUri [0..1]
}
class "SpatialExtent" as SpatialExtent #EEEEEE
SpatialExtent --> "0..1" Geometry : hasGeometry
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
Geometry ..> XsdAnyUri : crs

@enduml