@startuml
title QualityMeasure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "QualityMeasure" as QualityMeasure #FEFECE {
  +metric : XsdAnyUri [1]
  +value : string [1]
}
class "Dataset" as Dataset #EEEEEE
Dataset *-- "0..*" QualityMeasure : hasQualityMeasurement
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
QualityMeasure ..> XsdAnyUri : metric

@enduml