@startuml
title SentinelValueDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "SentinelValueDomain" as SentinelValueDomain #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable --> "0..*" SentinelValueDomain : takesSentinelValuesFrom
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
SentinelValueDomain ..> XsdAnyUri : identifier

@enduml