@startuml
title VariableMeasured
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "VariableMeasured" as VariableMeasured #FEFECE {
  +description : string [0..1]
  +propertyId : XsdAnyUri [0..*]
  +unitText : string [0..1]
  +unitCode : DefinedTerm [0..1]
  +physicalDataType : Concept [1]
  +role : string [0..1]
  +describedUnitOfMeasure : Concept [0..1]
  +minValue : string [0..1]
  +maxValue : string [0..1]
}
abstract class "AbstractVariable" as AbstractVariable #D6EAF8
AbstractVariable <|-- VariableMeasured
class "InstanceVariable" as InstanceVariable #EEEEEE
VariableMeasured --> "0..1" InstanceVariable : describes
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
VariableMeasured ..> XsdAnyUri : propertyId
class "DefinedTerm" as DefinedTerm #EEEEEE
VariableMeasured --> "0..1" DefinedTerm : unitCode
class "Concept" as Concept #EEEEEE
VariableMeasured --> "1" Concept : physicalDataType
VariableMeasured --> "0..1" Concept : describedUnitOfMeasure

@enduml