@startuml
title AbstractDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

abstract class "AbstractDataStructure" as AbstractDataStructure #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "DataStructure" as DataStructure #D5F5E3
AbstractDataStructure <|-- DataStructure
class "DimensionalDataStructure" as DimensionalDataStructure #D5F5E3
AbstractDataStructure <|-- DimensionalDataStructure
class "LongDataStructure" as LongDataStructure #D5F5E3
AbstractDataStructure <|-- LongDataStructure
class "WideDataStructure" as WideDataStructure #D5F5E3
AbstractDataStructure <|-- WideDataStructure
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..1" AbstractDataStructure : isStructuredBy
abstract class "DataStructureComponent" as DataStructureComponent #EEEEEE
AbstractDataStructure *-- "1..*" DataStructureComponent : hasComponent
class "PrimaryKey" as PrimaryKey #EEEEEE
AbstractDataStructure *-- "0..1" PrimaryKey : hasPrimaryKey
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
AbstractDataStructure ..> XsdAnyUri : identifier

@enduml