@startuml
title DataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataStructure" as DataStructure #FEFECE {
  +identifier : Identifier [1]
  +semantic : Concept [1..*]
}
class "ForeignKey" as ForeignKey #EEEEEE
DataStructure --> "0..*" ForeignKey : has
class "PhysicalDataSet" as PhysicalDataSet #EEEEEE
PhysicalDataSet --> "0..1" DataStructure : isStructuredBy

@enduml