@startuml
title DescriptorValueDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DescriptorValueDomain" as DescriptorValueDomain #FEFECE {
  +displayLabel : string [1..*]
  +identifier : Identifier [1]
  +recommendedDataType : Concept [1..*]
}
class "DescriptorVariable" as DescriptorVariable #EEEEEE
DescriptorVariable --> "1" DescriptorValueDomain : hasValuesFrom
class "Identifier" as Identifier #EEEEEE
DescriptorValueDomain --> "1" Identifier : identifier
class "Concept" as Concept #EEEEEE
DescriptorValueDomain --> "1..*" Concept : recommendedDataType

@enduml