@startuml
title DescriptorVariable
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DescriptorVariable" as DescriptorVariable #FEFECE {
  +identifier : Identifier [0..1]
  +name : string [0..*]
}
class "VariableDescriptorComponent" as VariableDescriptorComponent #EEEEEE
VariableDescriptorComponent --> "1" DescriptorVariable : isDefinedBy
class "DescriptorValueDomain" as DescriptorValueDomain #EEEEEE
DescriptorVariable --> "1" DescriptorValueDomain : hasValuesFrom
class "Identifier" as Identifier <<dataType>> #FAE5D3
DescriptorVariable ..> Identifier : identifier

@enduml