@startuml
title DimensionComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionComponent" as DimensionComponent #FEFECE {
  +type : string [1..*]
}
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" DimensionComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "1..*" DimensionComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "0..*" DimensionComponent : hasComponent

@enduml