@startuml
title DimensionComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionComponent" as DimensionComponent #FEFECE {
  +categoricalAdditivity : boolean [1]
}
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- DimensionComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure --> "1..*" DimensionComponent : has
class "ComponentPosition" as ComponentPosition #EEEEEE
ComponentPosition --> "1" DimensionComponent : indexes

@enduml