@startuml
title DimensionalDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionalDataStructure" as DimensionalDataStructure #FEFECE {
  +type : string [1..*]
}
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..1" DimensionalDataStructure : isStructuredBy
class "IdentifierComponent" as IdentifierComponent #EEEEEE
DimensionalDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "MeasureComponent" as MeasureComponent #EEEEEE
DimensionalDataStructure *-- "0..*" MeasureComponent : hasComponent
class "AttributeComponent" as AttributeComponent #EEEEEE
DimensionalDataStructure *-- "0..*" AttributeComponent : hasComponent
class "DimensionComponent" as DimensionComponent #EEEEEE
DimensionalDataStructure *-- "1..*" DimensionComponent : hasComponent
class "PrimaryKey" as PrimaryKey #EEEEEE
DimensionalDataStructure *-- "0..1" PrimaryKey : hasPrimaryKey
class "ForeignKey" as ForeignKey #EEEEEE
DimensionalDataStructure *-- "0..*" ForeignKey : hasForeignKey

@enduml