@startuml
title EnumerationDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "EnumerationDomain" as EnumerationDomain #FEFECE {
  +identifier : Identifier [1]
  +name : string [1..*]
  +purpose : string [1]
}

@enduml