@startuml
title MeasureComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "MeasureComponent" as MeasureComponent #FEFECE {
  +name : string [1..*]
}
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- MeasureComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure --> "1..*" MeasureComponent : has
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure --> "1..*" MeasureComponent : has
class "AttributeComponent" as AttributeComponent #EEEEEE
AttributeComponent --> "0..*" MeasureComponent : qualifies

@enduml