@startuml
title PrimaryKeyComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "PrimaryKeyComponent" as PrimaryKeyComponent #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
abstract class "AbstractDataStructureComponent" as AbstractDataStructureComponent #EEEEEE
PrimaryKeyComponent --> "0..1" AbstractDataStructureComponent : correspondsTo
class "ForeignKeyComponent" as ForeignKeyComponent #EEEEEE
ForeignKeyComponent --> "0..1" PrimaryKeyComponent : references
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
PrimaryKeyComponent ..> XsdAnyUri : identifier

@enduml