@startuml
title ProvActivity
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ProvActivity" as ProvActivity #FEFECE {
  +used : XsdAnyUri [0..*]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" ProvActivity : wasGeneratedBy
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ProvActivity ..> XsdAnyUri : used

@enduml