@startuml
title SentinelConceptualDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "SentinelConceptualDomain" as SentinelConceptualDomain #FEFECE {
  +displayLabel : string [1..*]
  +identifier : Identifier [1]
}
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain --> "0..1" SentinelConceptualDomain : takesConceptsFrom
class "ConceptSystem" as ConceptSystem #EEEEEE
SentinelConceptualDomain --> "0..1" ConceptSystem : takesConceptsFrom
class "Identifier" as Identifier #EEEEEE
SentinelConceptualDomain --> "1" Identifier : identifier

@enduml