@startuml
title VariableValueComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "VariableValueComponent" as VariableValueComponent #FEFECE
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- VariableValueComponent
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" VariableValueComponent : hasComponent
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure *-- "1" VariableValueComponent : hasComponent
class "VariableDescriptorComponent" as VariableDescriptorComponent #EEEEEE
VariableDescriptorComponent --> "1" VariableValueComponent : refersTo

@enduml