@startuml
title CatalogRecord
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "CatalogRecord" as CatalogRecord #FEFECE {
  +conformsTo : XsdAnyUri [1..*]
}
class "ConceptScheme" as ConceptScheme #EEEEEE
ConceptScheme *-- "1" CatalogRecord : subjectOf
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
CatalogRecord ..> XsdAnyUri : conformsTo

@enduml