@startuml
title Identifier
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Identifier" as Identifier #FEFECE {
  +propertyId : XsdAnyUri [1]
  +value : string [1]
  +url : XsdAnyUri [0..1]
}
class "ConceptScheme" as ConceptScheme #EEEEEE
ConceptScheme *-- "0..1" Identifier : identifier
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
Identifier ..> XsdAnyUri : propertyId

@enduml