@startuml
title ArchivePart
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "ArchivePart" as ArchivePart #FEFECE {
  +identifier : XsdAnyUri [0..1]
  +name : string [1]
  +description : string [0..1]
  +encodingFormat : string [1..*]
  +countColumns : integer [0..1]
  +countRows : integer [0..1]
}
class "DataDownload" as DataDownload #EEEEEE
DataDownload *-- "0..*" ArchivePart : hasPart
ArchivePart --> "0..*" ArchivePart : about
class "QuantitativeValue" as QuantitativeValue #EEEEEE
ArchivePart *-- "0..1" QuantitativeValue : size
class "Checksum" as Checksum #EEEEEE
ArchivePart *-- "0..1" Checksum : checksum
abstract class "AbstractMapping" as AbstractMapping #EEEEEE
ArchivePart *-- "0..*" AbstractMapping : hasPhysicalMapping
abstract class "AbstractDataSet" as AbstractDataSet #EEEEEE
ArchivePart o-- "0..1" AbstractDataSet : alsoTypedAs
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ArchivePart ..> XsdAnyUri : identifier

@enduml