@startuml
title Contributor
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Contributor" as Contributor #FEFECE {
  +roleName : DefinedTerm [1]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" Contributor : contributor
abstract class "Agent" as Agent #EEEEEE
Contributor --> "0..1" Agent : contributor
class "DefinedTerm" as DefinedTerm #EEEEEE
Contributor --> "1" DefinedTerm : roleName

@enduml