@startuml
title Person
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Person" as Person #FEFECE {
  +givenName : string [0..1]
  +familyName : string [0..1]
  +additionalName : string [0..*]
  +honorificPrefix : string [0..1]
  +honorificSuffix : string [0..1]
  +email : string [0..1]
  +telephone : string [0..1]
  +affiliation : string [0..*]
}
abstract class "Agent" as Agent #D6EAF8
Agent <|-- Person

@enduml