@startuml
title GeoShape
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "GeoShape" as GeoShape #FEFECE {
  +geometry : string [0..1]
  +box : string [0..1]
  +polygon : string [0..1]
  +line : string [0..1]
}
abstract class "AbstractGeometry" as AbstractGeometry #D6EAF8
AbstractGeometry <|-- GeoShape

@enduml