@startuml
title InstanceVariable
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "InstanceVariable" as InstanceVariable #FEFECE {
  +name : string [1]
  +definition : string [1]
  +describedUnitOfMeasure : Concept [0..1]
  +unitOfMeasureKind : Concept [0..1]
  +function : Concept [0..*]
  +platformType : Concept [0..1]
  +source : string [0..1]
  +hasIntendedDataType : Concept [0..1]
  +simpleUnitOfMeasure : string [0..1]
  +uses : Concept [0..*]
}
abstract class "AbstractVariable" as AbstractVariable #D6EAF8
AbstractVariable <|-- InstanceVariable
class "StatisticsCollection" as StatisticsCollection #EEEEEE
InstanceVariable --> "0..1" StatisticsCollection : isDescribedBy
InstanceVariable --> "0..1" InstanceVariable : qualifies
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
InstanceVariable --> "0..1" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
InstanceVariable --> "0..*" SentinelValueDomain : takesSentinelValuesFrom
class "VariableMeasured" as VariableMeasured #EEEEEE
VariableMeasured --> "0..1" InstanceVariable : describes
class "Statistics" as Statistics #EEEEEE
Statistics --> "1..*" InstanceVariable : appliesTo
Statistics --> "0..1" InstanceVariable : hasWeight
class "CategoryStatistics" as CategoryStatistics #EEEEEE
CategoryStatistics --> "0..1" InstanceVariable : hasWeight
StatisticsCollection --> "1..*" InstanceVariable : indexedBy
StatisticsCollection --> "0..1" InstanceVariable : hasWeight
class "PhysicalMapping" as PhysicalMapping #EEEEEE
PhysicalMapping --> "1" InstanceVariable : formats
class "Concept" as Concept #EEEEEE
InstanceVariable --> "0..1" Concept : describedUnitOfMeasure
InstanceVariable --> "0..1" Concept : unitOfMeasureKind
InstanceVariable --> "0..*" Concept : function
InstanceVariable --> "0..1" Concept : platformType
InstanceVariable --> "0..1" Concept : hasIntendedDataType
InstanceVariable --> "0..*" Concept : uses

@enduml