@startuml
title PhysicalMapping
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "PhysicalMapping" as PhysicalMapping #FEFECE {
  +index : integer [0..1]
  +format : string [0..1]
  +physicalDataType : string [0..1]
  +numberPattern : string [0..1]
  +nullSequence : string [0..1]
  +defaultValue : string [0..1]
  +scale : integer [0..1]
  +decimalPositions : integer [0..1]
  +minimumLength : integer [0..1]
  +maximumLength : integer [0..1]
  +isRequired : boolean [0..1]
}
class "TextMapping" as TextMapping #D5F5E3
PhysicalMapping <|-- TextMapping
class "LocatorMapping" as LocatorMapping #D5F5E3
PhysicalMapping <|-- LocatorMapping
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..*" PhysicalMapping : hasPhysicalMapping
class "InstanceVariable" as InstanceVariable #EEEEEE
PhysicalMapping --> "1" InstanceVariable : formats
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet --> "0..*" PhysicalMapping : hasPhysicalMapping
class "StructuredDataSet" as StructuredDataSet #EEEEEE
StructuredDataSet --> "0..*" PhysicalMapping : hasPhysicalMapping

@enduml