@startuml
title Statistics
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Statistics" as Statistics #FEFECE {
  +typeOfStatistic : Concept [0..1]
  +statistic : Statistic [1..*]
}
class "InstanceVariable" as InstanceVariable #EEEEEE
Statistics --> "1..*" InstanceVariable : appliesTo
Statistics --> "0..1" InstanceVariable : hasWeight
class "CategoryStatistics" as CategoryStatistics #EEEEEE
Statistics --> "0..*" CategoryStatistics : has
class "StatisticsCollection" as StatisticsCollection #EEEEEE
StatisticsCollection --> "1..*" Statistics : has
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" Statistics : statistics

@enduml