@startuml
title WebAPI
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "WebAPI" as WebAPI #FEFECE {
  +documentation : Reference [0..1]
  +url : XsdAnyUri [1]
}
abstract class "AbstractDistribution" as AbstractDistribution #D6EAF8
AbstractDistribution <|-- WebAPI
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
WebAPI ..> XsdAnyUri : url

@enduml