@startuml
title WebAPI
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "WebAPI" as WebAPI #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset *-- "0..*" WebAPI : distribution
class "ActionResult" as ActionResult #EEEEEE
WebAPI *-- "0..*" ActionResult : potentialActionResult
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
WebAPI ..> XsdAnyUri : identifier

@enduml