@startuml
title XsdDate
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdDate" as XsdDate <<dataType>> #FAE5D3
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdDate : dateModified
Dataset ..> XsdDate : datePublished
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdDate : sdDatePublished
class "TemporalExtent" as TemporalExtent #EEEEEE
TemporalExtent ..> XsdDate : startDate
TemporalExtent ..> XsdDate : endDate

@enduml