@startuml
title ActionResult
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ActionResult" as ActionResult #FEFECE {
  +name : string [0..1]
  +description : string [0..1]
  +encodingFormat : string [0..*]
  +conformsTo : XsdAnyUri [0..*]
}
class "Action" as Action #EEEEEE
Action --> "0..1" ActionResult : result
class "DataStructure" as DataStructure #EEEEEE
ActionResult --> "0..1" DataStructure : isStructuredBy
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ActionResult ..> XsdAnyUri : conformsTo

@enduml