@startuml
title Agent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

abstract class "Agent" as Agent #FEFECE {
  +identifier : Identifier [0..1]
  +name : string [0..1]
}
class "Person" as Person #D5F5E3
Agent <|-- Person
class "Organization" as Organization #D5F5E3
Agent <|-- Organization
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet --> "0..*" Agent : provider
class "StructuredDataSet" as StructuredDataSet #EEEEEE
StructuredDataSet --> "0..*" Agent : provider
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..*" Agent : provider
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" Agent : provider
Dataset --> "0..*" Agent : creator
Dataset --> "0..1" Agent : publisher
class "Contributor" as Contributor #EEEEEE
Contributor --> "0..1" Agent : contributor
class "MonetaryGrant" as MonetaryGrant #EEEEEE
MonetaryGrant --> "0..*" Agent : funder
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord --> "0..1" Agent : maintainer
class "Identifier" as Identifier #EEEEEE
Agent --> "0..1" Identifier : identifier

@enduml