@startuml
title DataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataStructure" as DataStructure #FEFECE {
  +identifier : Identifier [1]
  +semantic : Concept [1..*]
}
class "WideDataStructure" as WideDataStructure #D5F5E3
DataStructure <|-- WideDataStructure
class "LongDataStructure" as LongDataStructure #D5F5E3
DataStructure <|-- LongDataStructure
class "DimensionalDataStructure" as DimensionalDataStructure #D5F5E3
DataStructure <|-- DimensionalDataStructure
abstract class "DataStructureComponent" as DataStructureComponent #EEEEEE
DataStructure --> "1..*" DataStructureComponent : has
class "PrimaryKey" as PrimaryKey #EEEEEE
DataStructure --> "0..1" PrimaryKey : has
class "ForeignKey" as ForeignKey #EEEEEE
DataStructure --> "0..*" ForeignKey : has
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet --> "0..1" DataStructure : isStructuredBy
class "StructuredDataSet" as StructuredDataSet #EEEEEE
StructuredDataSet --> "0..1" DataStructure : isStructuredBy
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..1" DataStructure : isStructuredBy
class "ActionResult" as ActionResult #EEEEEE
ActionResult --> "0..1" DataStructure : isStructuredBy
class "Identifier" as Identifier #EEEEEE
DataStructure --> "1" Identifier : identifier
class "Concept" as Concept #EEEEEE
DataStructure --> "1..*" Concept : semantic

@enduml