@startuml
title DimensionGroup
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionGroup" as DimensionGroup #FEFECE {
  +identifier : XsdAnyUri [0..1]
  +name : string [1..*]
}
abstract class "AbstractDataStructureComponent" as AbstractDataStructureComponent #EEEEEE
DimensionGroup *-- "1..*" AbstractDataStructureComponent : hasComponent
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DimensionGroup ..> XsdAnyUri : identifier

@enduml