@startuml
title ForeignKey
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ForeignKey" as ForeignKey #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" ForeignKey : hasForeignKey
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "0..*" ForeignKey : hasForeignKey
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure *-- "0..*" ForeignKey : hasForeignKey
class "RepresentedVariable" as RepresentedVariable #EEEEEE
ForeignKey --> "1..*" RepresentedVariable : isComposedOf
class "PrimaryKey" as PrimaryKey #EEEEEE
ForeignKey --> "0..1" PrimaryKey : references
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ForeignKey ..> XsdAnyUri : identifier

@enduml