@startuml
title IdentifierComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "IdentifierComponent" as IdentifierComponent #FEFECE {
  +type : string [1..*]
}
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" IdentifierComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure *-- "1" IdentifierComponent : hasComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "0..*" IdentifierComponent : hasComponent

@enduml