@startuml
title LocatorMapping
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LocatorMapping" as LocatorMapping #FEFECE {
  +locator : string [1]
}
class "PhysicalMapping" as PhysicalMapping #D6EAF8
PhysicalMapping <|-- LocatorMapping

@enduml