@startuml
title PropertyValueSpecification
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "PropertyValueSpecification" as PropertyValueSpecification #FEFECE {
  +identifier : Identifier [0..1]
  +valueName : string [1]
  +description : string [1]
  +valueRequired : boolean [0..1]
  +valuePattern : string [0..1]
}
class "Action" as Action #EEEEEE
Action --> "0..*" PropertyValueSpecification : queryInput
class "Identifier" as Identifier #EEEEEE
PropertyValueSpecification --> "0..1" Identifier : identifier

@enduml