@startuml
title StructuredDataSet
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "StructuredDataSet" as StructuredDataSet #FEFECE {
  +encoding : string [0..1]
}
class "DataDownload" as DataDownload #D6EAF8
DataDownload <|-- StructuredDataSet

@enduml