@startuml
title SubstantiveValueDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "SubstantiveValueDomain" as SubstantiveValueDomain #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable --> "0..*" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable --> "0..1" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "ValueAndConceptDescription" as ValueAndConceptDescription #EEEEEE
SubstantiveValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
SubstantiveValueDomain ..> XsdAnyUri : identifier

@enduml