@startuml
title ValueAndConceptDescription
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ValueAndConceptDescription" as ValueAndConceptDescription #FEFECE {
  +classificationLevel : CategoryRelationCode [1]
  +description : InternationalString [1]
  +formatPattern : ControlledVocabularyEntry [1]
  +identifier : Identifier [1]
  +logicalExpression : ControlledVocabularyEntry [1]
  +maximumValueExclusive : string [1]
  +maximumValueInclusive : string [1]
  +minimumValueExclusive : string [1]
  +minimumValueInclusive : string [1]
  +regularExpression : string [1]
}
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
enum "CategoryRelationCode" as CategoryRelationCode <<enumeration>> #F9E79F
{
  Continuous
  Interval
  Nominal
  Ordinal
  Ratio
}
ValueAndConceptDescription ..> CategoryRelationCode : classificationLevel
class "InternationalString" as InternationalString <<dataType>> #FAE5D3
ValueAndConceptDescription ..> InternationalString : description
class "ControlledVocabularyEntry" as ControlledVocabularyEntry <<dataType>> #FAE5D3
ValueAndConceptDescription ..> ControlledVocabularyEntry : formatPattern
class "Identifier" as Identifier <<dataType>> #FAE5D3
ValueAndConceptDescription ..> Identifier : identifier

@enduml