@startuml
title WideDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "WideDataStructure" as WideDataStructure #FEFECE {
  +type : string [1..*]
}
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..1" WideDataStructure : isStructuredBy
class "IdentifierComponent" as IdentifierComponent #EEEEEE
WideDataStructure *-- "0..*" IdentifierComponent : hasComponent
class "MeasureComponent" as MeasureComponent #EEEEEE
WideDataStructure *-- "0..*" MeasureComponent : hasComponent
class "AttributeComponent" as AttributeComponent #EEEEEE
WideDataStructure *-- "0..*" AttributeComponent : hasComponent
class "PrimaryKey" as PrimaryKey #EEEEEE
WideDataStructure *-- "0..1" PrimaryKey : hasPrimaryKey
class "ForeignKey" as ForeignKey #EEEEEE
WideDataStructure *-- "0..*" ForeignKey : hasForeignKey

@enduml