@startuml
title DateRange
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "DateRange" as DateRange <<dataType>> #FAE5D3 {
  +endDate : CombinedDate [1]
  +startDate : CombinedDate [1]
}

@enduml