@startuml
title EmbargoInformation
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "EmbargoInformation" as EmbargoInformation <<dataType>> #FAE5D3 {
  +description : InternationalString [1]
  +period : DateRange [1..*]
}

@enduml