@startuml
title LicenseInformation
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "LicenseInformation" as LicenseInformation <<dataType>> #FAE5D3 {
  +contact : ContactInformation [1..*]
  +description : InternationalString [1..*]
  +licenseAgent : AgentInRole [1..*]
  +licenseReference : Reference [1..*]
}

@enduml