@startuml
title ObjectName
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ObjectName" as ObjectName <<dataType>> #FAE5D3 {
  +context : ControlledVocabularyEntry [1]
  +name : string [1]
}
class "MeasureComponent" as MeasureComponent #EEEEEE
MeasureComponent ..> ObjectName : name
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable ..> ObjectName : name
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable ..> ObjectName : name
class "EnumerationDomain" as EnumerationDomain #EEEEEE
EnumerationDomain ..> ObjectName : name
class "UnitType" as UnitType #EEEEEE
UnitType ..> ObjectName : name
class "PhysicalDataSet" as PhysicalDataSet #EEEEEE
PhysicalDataSet ..> ObjectName : name

@enduml