@startuml
title Reference
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "Reference" as Reference <<dataType>> #FAE5D3 {
  +ddiReference : InternationalRegistrationDataIdentifier [1]
  +deepLink : Selector [1]
  +description : string [1]
  +location : InternationalString [1]
  +nonDdiReference : NonDdiIdentifier [1..*]
  +semantic : ControlledVocabularyEntry [1]
  +uri : XsdAnyUri [1]
  +validType : string [1..*]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable ..> Reference : externalDefinition
class "DescriptorVariable" as DescriptorVariable #EEEEEE
DescriptorVariable ..> Reference : source
DescriptorVariable ..> Reference : externalDefinition
class "UnitType" as UnitType #EEEEEE
UnitType ..> Reference : externalDefinition

@enduml