@startuml
title TableDirectionValues
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

enum "TableDirectionValues" as TableDirectionValues <<enumeration>> #F9E79F
{
  Auto
  Ltr
  Rtl
}
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet ..> TableDirectionValues : tableDirection

@enduml