@startuml
title Telephone
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "Telephone" as Telephone <<dataType>> #FAE5D3 {
  +effectiveDates : DateRange [1]
  +isPreferred : boolean [1]
  +privacy : ControlledVocabularyEntry [1]
  +telephoneNumber : string [1]
  +typeOfTelephone : ControlledVocabularyEntry [1]
}

@enduml