@startuml
title TextDirectionValues
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

enum "TextDirectionValues" as TextDirectionValues <<enumeration>> #F9E79F
{
  Auto
  Inherit
  Ltr
  Rtl
}
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet ..> TextDirectionValues : textDirection

@enduml