@startuml
title TrimValues
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

enum "TrimValues" as TrimValues <<enumeration>> #F9E79F
{
  Both
  End
  Neither
  Start
}
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet ..> TrimValues : trim

@enduml