@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "DataDownload" as DataDownload #EEEEEE
DataDownload ..> XsdAnyUri : identifier
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup ..> XsdAnyUri : identifier
class "PrimaryKey" as PrimaryKey #EEEEEE
PrimaryKey ..> XsdAnyUri : identifier
class "ForeignKey" as ForeignKey #EEEEEE
ForeignKey ..> XsdAnyUri : identifier
class "DefinedTerm" as DefinedTerm #EEEEEE
DefinedTerm ..> XsdAnyUri : identifier
DefinedTerm ..> XsdAnyUri : inDefinedTermSet
class "CdifConceptOrTerm" as CdifConceptOrTerm #EEEEEE
CdifConceptOrTerm ..> XsdAnyUri : identifier

@enduml