@startuml
title LanguageTaggedValue
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LanguageTaggedValue" as LanguageTaggedValue <<dataType>> #FAE5D3 {
  +@value : String [1]
  +@language : String [0..1]
}

@enduml
