@startuml
title Contributor
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Contributor" as Contributor #FEFECE {
  +roleName : DefinedTerm [1]
  +startDate : XsdDate [0..1]
  +endDate : XsdDate [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset "0..*" <-- Contributor : contributor
abstract class "Agent" as Agent #EEEEEE
Contributor --> "0..1" Agent : agent
class "XsdDate" as XsdDate <<dataType>> #FAE5D3
Contributor ..> XsdDate : startDate

@enduml