@startuml
title DataDownload
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataDownload" as DataDownload #FEFECE {
  +contentUrl : XsdAnyUri [0..1]
  +encodingFormat : DefinedTerm [0..*]
  +contentSize : string [0..1]
  +checksum : string [0..*]
  +conformsTo : XsdAnyUri [0..*]
}
abstract class "AbstractDistribution" as AbstractDistribution #D6EAF8
AbstractDistribution <|-- DataDownload
abstract class "Agent" as Agent #EEEEEE
DataDownload --> "0..*" Agent : provider
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DataDownload ..> XsdAnyUri : contentUrl
class "DefinedTerm" as DefinedTerm #EEEEEE
DataDownload --> "0..*" DefinedTerm : encodingFormat

@enduml