'$schema': 'https://json-schema.org/draft/2020-12/schema'
title: DDI-CDI Enumeration Domain
description: >-
  A base class acting as an extension point to allow all codifications (codelist, statistical
  classification, etc.) to be understood as enumerated value domains.
type: object
properties:
  '@type':
    type: array
    items:
      type: string
    contains:
      const: 'cdi:EnumerationDomain'
    minItems: 1
  '@id':
    type: string
    description: Identifier for this EnumerationDomain node
  'cdi:identifier':
    '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/Identifier'
    description: >-
      Identifier for objects requiring short- or long-lasting referencing and management.
  'cdi:name':
    type: array
    items:
      '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/ObjectName'
    minItems: 1
    description: >-
      Human understandable name (liguistic signifier, word, phrase, or mnemonic). May follow
      ISO/IEC 11179-5 naming principles, and have context provided to specify usage.
  'cdi:uses':
    '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/id-reference'
  'cdi:references':
    '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/id-reference'
  'cdi:isDefinedBy':
    type: array
    items:
      '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/id-reference'
    minItems: 1
  'cdi:purpose':
    '$ref': '../ddicdiDataTypes/schema.yaml#/$defs/InternationalString'
    description: Intent or reason for the object/the description of the object.
required:
- '@type'
