@startuml
title ActionResult
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ActionResult" as ActionResult #FEFECE {
  +characterSet : string [0..1]
}
class "WebAPI" as WebAPI #EEEEEE
WebAPI *-- "0..*" ActionResult : potentialActionResult
abstract class "AbstractMapping" as AbstractMapping #EEEEEE
ActionResult *-- "0..*" AbstractMapping : hasPhysicalMapping

@enduml