@startuml
title AdditionalProperty
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "AdditionalProperty" as AdditionalProperty #FEFECE {
  +propertyId : string [1]
  +name : string [0..1]
  +value : string [1]
  +unitText : string [0..1]
  +unitCode : XsdAnyUri [0..1]
}
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
AdditionalProperty ..> XsdAnyUri : unitCode

@enduml