@startuml
title CategoryStatistics
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "CategoryStatistics" as CategoryStatistics #FEFECE {
  +typeOfStatistic : Concept [0..1]
  +statistic : Statistic [1..*]
}
class "Statistics" as Statistics #EEEEEE
Statistics --> "0..*" CategoryStatistics : has
class "Category" as Category #EEEEEE
CategoryStatistics --> "1" Category : for
class "InstanceVariable" as InstanceVariable #EEEEEE
CategoryStatistics --> "0..1" InstanceVariable : hasWeight

@enduml