@startuml
title DataDownload
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataDownload" as DataDownload #FEFECE {
  +characterSet : string [0..1]
  +fileSize : integer [0..1]
  +fileSizeUofM : string [0..1]
  +contentUrl : XsdAnyUri [0..1]
  +url : XsdAnyUri [0..1]
  +encodingFormat : DefinedTerm [0..*]
  +contentSize : string [0..1]
  +dateModified : XsdDate [0..1]
  +datePublished : XsdDate [0..1]
  +license : Reference [0..*]
  +conditionsOfAccess : Reference [0..*]
  +checksum : string [0..*]
}
abstract class "AbstractDistribution" as AbstractDistribution #D6EAF8
AbstractDistribution <|-- DataDownload
class "PhysicalMapping" as PhysicalMapping #EEEEEE
DataDownload --> "0..*" PhysicalMapping : hasPhysicalMapping
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DataDownload ..> XsdAnyUri : contentUrl
class "XsdDate" as XsdDate <<dataType>> #FAE5D3
DataDownload ..> XsdDate : dateModified

@enduml