@startuml
title DataDownload
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataDownload" as DataDownload #FEFECE {
  +characterSet : string [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset *-- "0..*" DataDownload : distribution
abstract class "AbstractMapping" as AbstractMapping #EEEEEE
DataDownload *-- "0..*" AbstractMapping : hasPhysicalMapping
abstract class "AbstractDataSet" as AbstractDataSet #EEEEEE
DataDownload o-- "0..1" AbstractDataSet : alsoTypedAs
class "DataFingerprint" as DataFingerprint #EEEEEE
DataDownload *-- "0..1" DataFingerprint : fingerprint

@enduml