@startuml
title EnumerationDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "EnumerationDomain" as EnumerationDomain #FEFECE {
  +identifier : Identifier [0..1]
  +name : string [0..1]
  +references : XsdAnyUri [1]
  +purpose : string [0..1]
}
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain --> "0..1" EnumerationDomain : takesValuesFrom
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain --> "0..1" EnumerationDomain : takesValuesFrom
class "Identifier" as Identifier #EEEEEE
EnumerationDomain --> "0..1" Identifier : identifier
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
EnumerationDomain ..> XsdAnyUri : references

@enduml