@startuml
title Reference
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Reference" as Reference #FEFECE {
  +identifier : Identifier [1]
  +name : string [0..1]
  +description : string [0..1]
  +url : XsdAnyUri [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset "0..*" <-- Reference : license
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
Reference ..> XsdAnyUri : url

@enduml