@startuml
title CompositeProfile
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

abstract class "CompositeProfile" as CompositeProfile #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
CompositeProfile ..> XsdAnyUri : identifier

@enduml