@startuml
title DimensionComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionComponent" as DimensionComponent #FEFECE {
  +type : string [1..*]
}
abstract class "AbstractDataStructureComponent" as AbstractDataStructureComponent #D6EAF8
AbstractDataStructureComponent <|-- DimensionComponent

@enduml