@startuml
title DimensionalDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionalDataStructure" as DimensionalDataStructure #FEFECE {
  +type : string [1..*]
}
abstract class "AbstractDataStructure" as AbstractDataStructure #D6EAF8
AbstractDataStructure <|-- DimensionalDataStructure

@enduml