@startuml
title EntryPoint
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "EntryPoint" as EntryPoint #FEFECE {
  +description : string [0..1]
  +urlTemplate : string [1]
  +httpMethod : string [0..*]
  +contentType : string [0..*]
}
class "Action" as Action #EEEEEE
Action --> "1" EntryPoint : target

@enduml