@startuml
title LongDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LongDataStructure" as LongDataStructure #FEFECE {
  +type : string [1..*]
}
class "DataDownload" as DataDownload #EEEEEE
DataDownload --> "0..1" LongDataStructure : isStructuredBy
class "IdentifierComponent" as IdentifierComponent #EEEEEE
LongDataStructure *-- "1" IdentifierComponent : hasComponent
class "VariableDescriptorComponent" as VariableDescriptorComponent #EEEEEE
LongDataStructure *-- "1" VariableDescriptorComponent : hasComponent
class "VariableValueComponent" as VariableValueComponent #EEEEEE
LongDataStructure *-- "1" VariableValueComponent : hasComponent
class "AttributeComponent" as AttributeComponent #EEEEEE
LongDataStructure *-- "0..*" AttributeComponent : hasComponent
class "PrimaryKey" as PrimaryKey #EEEEEE
LongDataStructure *-- "0..1" PrimaryKey : hasPrimaryKey

@enduml