@startuml
title LongDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LongDataStructure" as LongDataStructure #FEFECE {
  +type : string [1..*]
}
abstract class "AbstractDataStructure" as AbstractDataStructure #D6EAF8
AbstractDataStructure <|-- LongDataStructure

@enduml