@startuml
title MeasureComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "MeasureComponent" as MeasureComponent #FEFECE {
  +type : string [1..*]
}
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" MeasureComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "0..*" MeasureComponent : hasComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure *-- "0..*" MeasureComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "0..*" MeasureComponent : hasComponent

@enduml