@startuml
title Concept
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "Concept" as Concept #FEFECE {
  +identifier : XsdAnyUri [0..1]
  +prefLabel : string [1..*]
  +notation : string [1..*]
  +definition : string [0..*]
  +note : string [0..*]
}
class "ConceptScheme" as ConceptScheme #EEEEEE
ConceptScheme *-- "1..*" Concept : hasTopConcept
Concept --> "0..*" ConceptScheme : inScheme
Concept --> "0..*" Concept : broader
Concept --> "0..*" Concept : narrower
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
Concept ..> XsdAnyUri : identifier

@enduml