@startuml
title ConceptRef
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ConceptRef" as ConceptRef #FEFECE {
  +identifier : String [1]
}

@enduml
