@startuml
title Concept
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Concept" as Concept #FEFECE {
  +identifier : String [0..1]
  +type : String [1..*]
  +notation : String [1..*]
  +inScheme : @id-ref [0..1]
}

class "LanguageTaggedValue" as LanguageTaggedValue <<dataType>> #FAE5D3

class "ConceptRef" as ConceptRef #FEFECE

Concept --> "1" LanguageTaggedValue : prefLabel
Concept --> "0..1" LanguageTaggedValue : definition
Concept --> "0..1" LanguageTaggedValue : note
Concept --> "0..*" ConceptRef : broader
Concept --> "0..*" ConceptRef : narrower
@enduml
