@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdAnyUri : identifier
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo
class "ArchivePart" as ArchivePart #EEEEEE
ArchivePart ..> XsdAnyUri : identifier

@enduml