@startuml
title Checksum
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Checksum" as Checksum #FEFECE {
  +algorithm : string [1]
  +checksumValue : string [1]
}
class "ArchivePart" as ArchivePart #EEEEEE
ArchivePart *-- "0..1" Checksum : checksum

@enduml