@startuml
title PhysicalMapping
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "PhysicalMapping" as PhysicalMapping #FEFECE {
  +index : integer [0..1]
  +format : string [0..1]
  +physicalDataType : string [0..1]
}
abstract class "AbstractMapping" as AbstractMapping #D6EAF8
AbstractMapping <|-- PhysicalMapping

@enduml