@startuml
title DataDescriptionWithStructure — overview
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataStructure" as DataStructure #FEFECE
class "WideDataStructure" as WideDataStructure #FEFECE
class "LongDataStructure" as LongDataStructure #FEFECE
class "DimensionalDataStructure" as DimensionalDataStructure #FEFECE
abstract class "DataStructureComponent" as DataStructureComponent #FEFECE
class "IdentifierComponent" as IdentifierComponent #FEFECE
class "MeasureComponent" as MeasureComponent #FEFECE
class "AttributeComponent" as AttributeComponent #FEFECE
class "DimensionComponent" as DimensionComponent #FEFECE
class "VariableValueComponent" as VariableValueComponent #FEFECE
class "VariableDescriptorComponent" as VariableDescriptorComponent #FEFECE
class "ComponentPosition" as ComponentPosition #FEFECE
class "PrimaryKey" as PrimaryKey #FEFECE
class "PrimaryKeyComponent" as PrimaryKeyComponent #FEFECE
class "RepresentedVariable" as RepresentedVariable #FEFECE
class "DescriptorVariable" as DescriptorVariable #FEFECE
class "InstanceVariable" as InstanceVariable #FEFECE
class "SubstantiveValueDomain" as SubstantiveValueDomain #FEFECE
class "SentinelValueDomain" as SentinelValueDomain #FEFECE
class "DescriptorValueDomain" as DescriptorValueDomain #FEFECE
class "EnumerationDomain" as EnumerationDomain #FEFECE
class "ForeignKey" as ForeignKey #FEFECE
class "ForeignKeyComponent" as ForeignKeyComponent #FEFECE
class "ValueAndConceptDescription" as ValueAndConceptDescription #FEFECE
class "UnitType" as UnitType #FEFECE
class "PhysicalDataSet" as PhysicalDataSet #FEFECE
class "TabularTextDataSet" as TabularTextDataSet #FEFECE
class "StructuredDataSet" as StructuredDataSet #FEFECE
abstract class "AbstractVariable" as AbstractVariable #FEFECE
class "VariableMeasured" as VariableMeasured #FEFECE
class "DataDownload" as DataDownload #FEFECE
class "Statistic" as Statistic #FEFECE
class "Statistics" as Statistics #FEFECE
class "CategoryStatistics" as CategoryStatistics #FEFECE
class "StatisticsCollection" as StatisticsCollection #FEFECE
class "Category" as Category #FEFECE
class "PhysicalMapping" as PhysicalMapping #FEFECE
class "TextMapping" as TextMapping #FEFECE
class "LocatorMapping" as LocatorMapping #FEFECE
class "DataFingerprint" as DataFingerprint #FEFECE
class "Concept" as Concept #FEFECE
class "Identifier" as Identifier #FEFECE
class "DefinedTerm" as DefinedTerm #FEFECE
class "Dataset" as Dataset #FEFECE
class "SpatialExtent" as SpatialExtent #FEFECE
abstract class "AbstractGeometry" as AbstractGeometry #FEFECE
class "GeoCoordinates" as GeoCoordinates #FEFECE
class "GeoShape" as GeoShape #FEFECE
class "TemporalExtent" as TemporalExtent #FEFECE
class "Instant" as Instant #FEFECE
class "TimePosition" as TimePosition #FEFECE
class "Geometry" as Geometry #FEFECE
class "QualityMeasurement" as QualityMeasurement #FEFECE
abstract class "AbstractDistribution" as AbstractDistribution #D6EAF8
class "WebAPI" as WebAPI #D6EAF8
class "Action" as Action #D6EAF8
class "EntryPoint" as EntryPoint #D6EAF8
class "ActionResult" as ActionResult #D6EAF8
class "PropertyValueSpecification" as PropertyValueSpecification #D6EAF8
abstract class "Agent" as Agent #D6EAF8
class "Person" as Person #D6EAF8
class "ContactPoint" as ContactPoint #D6EAF8
class "Organization" as Organization #D6EAF8
class "Contributor" as Contributor #D6EAF8
class "AdditionalProperty" as AdditionalProperty #D6EAF8
class "Reference" as Reference #D6EAF8
class "MonetaryGrant" as MonetaryGrant #D6EAF8
class "ProvActivity" as ProvActivity #FEFECE
class "DerivedFrom" as DerivedFrom #D6EAF8
class "CatalogRecord" as CatalogRecord #FEFECE
DataStructure <|-- WideDataStructure
DataStructure <|-- LongDataStructure
DataStructure <|-- DimensionalDataStructure
DataStructureComponent <|-- IdentifierComponent
DataStructureComponent <|-- MeasureComponent
DataStructureComponent <|-- AttributeComponent
DataStructureComponent <|-- DimensionComponent
DataStructureComponent <|-- VariableValueComponent
AbstractVariable <|-- InstanceVariable
DataDownload <|-- TabularTextDataSet
DataDownload <|-- StructuredDataSet
AbstractVariable <|-- VariableMeasured
AbstractDistribution <|-- DataDownload
PhysicalMapping <|-- TextMapping
PhysicalMapping <|-- LocatorMapping
AbstractGeometry <|-- GeoCoordinates
AbstractGeometry <|-- GeoShape
AbstractDistribution <|-- WebAPI
Agent <|-- Person
Agent <|-- Organization
DataStructure --> "1..*" DataStructureComponent : has
DataStructure --> "0..1" PrimaryKey : has
DataStructure --> "0..*" ForeignKey : has
WideDataStructure --> "1..*" IdentifierComponent : has
WideDataStructure --> "1..*" MeasureComponent : has
WideDataStructure --> "0..*" AttributeComponent : has
LongDataStructure --> "1..*" IdentifierComponent : has
LongDataStructure --> "1..*" VariableDescriptorComponent : has
LongDataStructure --> "1..*" VariableValueComponent : has
LongDataStructure --> "0..*" AttributeComponent : has
DimensionalDataStructure --> "0..*" IdentifierComponent : has
DimensionalDataStructure --> "1..*" DimensionComponent : has
DimensionalDataStructure --> "1..*" MeasureComponent : has
DimensionalDataStructure --> "0..*" AttributeComponent : has
DimensionalDataStructure --> "1..*" ComponentPosition : has
DataStructureComponent --> "1" RepresentedVariable : isDefinedBy
AttributeComponent --> "0..*" MeasureComponent : qualifies
VariableDescriptorComponent --> "1" DescriptorVariable : isDefinedBy
VariableDescriptorComponent --> "0..1" VariableValueComponent : refersTo
ComponentPosition --> "1" DimensionComponent : indexes
PrimaryKey --> "1..*" PrimaryKeyComponent : isComposedOf
PrimaryKeyComponent --> "1" IdentifierComponent : correspondsTo
PrimaryKeyComponent --> "1" InstanceVariable : indexes
RepresentedVariable --> "0..*" SubstantiveValueDomain : takesSubstantiveValuesFrom
RepresentedVariable --> "0..*" SentinelValueDomain : takesSentinelValuesFrom
RepresentedVariable --> "0..*" Concept : uses
RepresentedVariable --> "0..1" UnitType : measures
DescriptorVariable --> "1" DescriptorValueDomain : hasValuesFrom
InstanceVariable --> "1" RepresentedVariable : uses
InstanceVariable --> "0..1" StatisticsCollection : isDescribedBy
InstanceVariable --> "0..1" InstanceVariable : qualifies
InstanceVariable --> "0..1" SubstantiveValueDomain : takesSubstantiveValuesFrom
InstanceVariable --> "0..*" SentinelValueDomain : takesSentinelValuesFrom
SubstantiveValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
SubstantiveValueDomain --> "0..1" EnumerationDomain : takesValuesFrom
SentinelValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
SentinelValueDomain --> "0..1" EnumerationDomain : takesValuesFrom
EnumerationDomain --> "0..1" Concept : isDefinedBy
ForeignKey --> "1..*" ForeignKeyComponent : isComposedOf
ForeignKeyComponent --> "1" DataStructureComponent : correspondsTo
ForeignKeyComponent --> "1" PrimaryKeyComponent : references
VariableMeasured --> "0..1" InstanceVariable : describes
DataDownload --> "0..1" DataStructure : isStructuredBy
DataDownload --> "0..*" PhysicalMapping : hasPhysicalMapping
DataDownload --> "0..*" Agent : provider
Statistics --> "1..*" InstanceVariable : appliesTo
Statistics --> "0..1" InstanceVariable : hasWeight
Statistics --> "0..*" CategoryStatistics : has
CategoryStatistics --> "1" Category : for
CategoryStatistics --> "0..1" InstanceVariable : hasWeight
StatisticsCollection --> "1..*" Statistics : has
StatisticsCollection --> "1..*" InstanceVariable : indexedBy
StatisticsCollection --> "0..1" InstanceVariable : hasWeight
PhysicalMapping --> "1" InstanceVariable : formats
Dataset --> "1..*" AbstractVariable : variableMeasured
Dataset --> "0..1" PrimaryKey : hasPrimaryKey
Dataset --> "0..*" Statistics : statistics
Dataset --> "0..*" StatisticsCollection : statisticsCollection
Dataset --> "0..*" SpatialExtent : spatialCoverage
Dataset --> "0..*" TemporalExtent : temporalCoverage
Dataset --> "0..*" QualityMeasurement : hasQualityMeasurement
Dataset --> "0..*" Agent : provider
Dataset --> "0..*" AbstractDistribution : distribution
Dataset --> "0..*" Agent : creator
Dataset --> "0..*" Contributor : contributor
Dataset --> "0..1" Agent : publisher
Dataset --> "0..*" MonetaryGrant : funding
Dataset --> "0..*" ProvActivity : wasGeneratedBy
Dataset --> "0..*" DerivedFrom : wasDerivedFrom
Dataset --> "1" CatalogRecord : subjectOf
Dataset --> "0..*" DefinedTerm : keywords
Dataset --> "0..*" Reference : license
SpatialExtent --> "0..1" AbstractGeometry : geo
SpatialExtent --> "0..1" Geometry : hasGeometry
TemporalExtent --> "0..1" Instant : hasBeginning
TemporalExtent --> "0..1" Instant : hasEnd
Instant --> "0..1" TimePosition : inTimePosition
WebAPI --> "0..*" Action : potentialAction
Action --> "1" EntryPoint : target
Action --> "0..1" ActionResult : result
Action --> "0..*" PropertyValueSpecification : queryInput
ActionResult --> "0..1" DataStructure : isStructuredBy
Contributor --> "0..1" Agent : contributor
MonetaryGrant --> "0..*" Agent : funder
CatalogRecord --> "0..1" Dataset : about
CatalogRecord --> "0..1" Agent : maintainer

@enduml