@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdAnyUri : identifier
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo
class "ArchivePart" as ArchivePart #EEEEEE
ArchivePart ..> XsdAnyUri : identifier
class "DefinedTerm" as DefinedTerm #EEEEEE
DefinedTerm ..> XsdAnyUri : identifier
DefinedTerm ..> XsdAnyUri : inDefinedTermSet
abstract class "AbstractMapping" as AbstractMapping #EEEEEE
AbstractMapping ..> XsdAnyUri : identifier
abstract class "AbstractDataSet" as AbstractDataSet #EEEEEE
AbstractDataSet ..> XsdAnyUri : identifier

@enduml