@startuml
title TypedString
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "TypedString" as TypedString <<dataType>> #FAE5D3 {
  +content : string [1]
  +typeOfContent : ControlledVocabularyEntry [1]
}
class "ValueAndConceptDescription" as ValueAndConceptDescription #EEEEEE
ValueAndConceptDescription ..> TypedString : regularExpression

@enduml