@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdAnyUri : identifier
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo
class "WebAPI" as WebAPI #EEEEEE
WebAPI ..> XsdAnyUri : identifier
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable ..> XsdAnyUri : identifier
abstract class "AbstractMapping" as AbstractMapping #EEEEEE
AbstractMapping ..> XsdAnyUri : identifier
abstract class "AbstractDataSet" as AbstractDataSet #EEEEEE
AbstractDataSet ..> XsdAnyUri : identifier
class "PrimaryKey" as PrimaryKey #EEEEEE
PrimaryKey ..> XsdAnyUri : identifier
class "Statistics" as Statistics #EEEEEE
Statistics ..> XsdAnyUri : identifier
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain ..> XsdAnyUri : identifier
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain ..> XsdAnyUri : identifier

@enduml