---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: CDIF complete metadata schema
description: >-
  CDIF complete profile combining core metadata with discovery properties,
  data description, archive distribution, and provenance extensions.
allOf:
- $ref: ../../../cdifProperties/cdifCore/schema.yaml
- $ref: ../../../cdifProperties/cdifDataDescription/schema.yaml
- $ref: ../../../cdifProperties/cdifArchiveDistribution/schema.yaml
- $ref: ../../../cdifProperties/cdifProvenance/schema.yaml
- type: object
  properties:
    '@context':
      type: object
      description: Additional JSON-LD namespace prefixes for complete profile.
      properties:
        geosparql:
          const: "http://www.opengis.net/ont/geosparql#"
        dqv:
          const: "http://www.w3.org/ns/dqv#"
        cdi:
          const: "http://ddialliance.org/Specification/DDI-CDI/1.0/RDF/"
    'schema:measurementTechnique':
      description: The technique, technology, or methodology used for measurement or
        determination of the dataset values.
      anyOf:
      - type: string
      - $ref: '#/$defs/DefinedTerm'
      - type: array
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/DefinedTerm'
    'schema:spatialCoverage':
      description: Geographic extent of resource content.
      type: array
      items:
        $ref: '#/$defs/SpatialExtent'
    'schema:temporalCoverage':
      description: Temporal extent of resource content.
      type: array
      items:
        $ref: '#/$defs/TemporalExtent'
    'dqv:hasQualityMeasurement':
      description: Quality measurements reported to assess the resource.
      type: array
      items:
        $ref: '#/$defs/QualityMeasure'
    'schema:subjectOf':
      properties:
        'dcterms:conformsTo':
          allOf:
          - contains:
              type: object
              properties:
                '@id':
                  const: 'https://w3id.org/cdif/discovery/1.0'
          - contains:
              type: object
              properties:
                '@id':
                  const: 'https://w3id.org/cdif/data_description/1.0'
          - contains:
              type: object
              properties:
                '@id':
                  const: 'https://w3id.org/cdif/manifest/1.0'
          - contains:
              type: object
              properties:
                '@id':
                  const: 'https://w3id.org/cdif/provenance/1.0'
$defs:
  DefinedTerm:
    $ref: ../../../schemaorgProperties/definedTerm/schema.yaml
  SpatialExtent:
    $ref: ../../../schemaorgProperties/spatialExtent/schema.yaml
  TemporalExtent:
    $ref: ../../../schemaorgProperties/temporalExtent/schema.yaml
  QualityMeasure:
    $ref: ../../../qualityProperties/qualityMeasure/schema.yaml
