@startuml
title XsdDate
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "XsdDate" as XsdDate <<dataType>> #FAE5D3
class "TemporalExtent" as TemporalExtent #EEEEEE
TemporalExtent ..> XsdDate : startDate
TemporalExtent ..> XsdDate : endDate

@enduml