@startuml
title SpatialExtent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "SpatialExtent" as SpatialExtent #FEFECE {
  +identifier : XsdAnyUri [0..1]
  +name : string [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset *-- "0..*" SpatialExtent : spatialCoverage
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
SpatialExtent ..> XsdAnyUri : identifier

@enduml