@startuml
title GeoCoordinates
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "GeoCoordinates" as GeoCoordinates #FEFECE {
  +latitude : string [0..1]
  +longitude : string [0..1]
}
abstract class "AbstractGeometry" as AbstractGeometry #D6EAF8
AbstractGeometry <|-- GeoCoordinates

@enduml