@startuml
title GeoShape
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "GeoShape" as GeoShape #FEFECE {
  +box : string [0..1]
  +line : string [0..1]
}
abstract class "AbstractGeometry" as AbstractGeometry #D6EAF8
AbstractGeometry <|-- GeoShape

@enduml