@startuml
title ConceptScheme
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ConceptScheme" as ConceptScheme #FEFECE {
  +identifier : XsdAnyUri [1]
  +prefLabel : string [1]
  +definition : string [0..1]
  +note : string [0..1]
  +dateModified : XsdDate [1]
  +url : XsdAnyUri [0..1]
  +license : string [0..*]
  +conditionsOfAccess : string [0..*]
}
class "CatalogRecord" as CatalogRecord #EEEEEE
ConceptScheme *-- "1" CatalogRecord : subjectOf
class "Identifier" as Identifier #EEEEEE
ConceptScheme *-- "0..1" Identifier : identifier
class "Concept" as Concept #EEEEEE
ConceptScheme *-- "1..*" Concept : hasTopConcept
Concept --> "1..*" ConceptScheme : inScheme
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ConceptScheme ..> XsdAnyUri : identifier
class "XsdDate" as XsdDate <<dataType>> #FAE5D3
ConceptScheme ..> XsdDate : dateModified

@enduml