@startuml
title Concept
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Concept" as Concept #FEFECE {
  +prefLabel : string [1..*]
  +altLabel : string [0..*]
  +hiddenLabel : string [0..*]
  +notation : string [0..*]
  +definition : string [1..*]
  +scopeNote : string [0..*]
  +note : string [0..*]
  +historyNote : string [0..*]
  +changeNote : string [0..*]
  +editorialNote : string [0..*]
  +example : string [0..*]
  +identifier : Identifier [1]
}
class "ConceptScheme" as ConceptScheme #EEEEEE
ConceptScheme "1..*" <-- Concept : hasTopConcept
Concept --> "1..*" ConceptScheme : inScheme
Concept --> "0..*" Concept : broader
Concept --> "0..*" Concept : narrower
Concept --> "0..*" Concept : related
Concept --> "0..*" Concept : exactMatch
Concept --> "0..*" Concept : closeMatch

@enduml