@startuml
title CatalogRecord
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "CatalogRecord" as CatalogRecord #FEFECE {
  +conformsTo : XsdAnyUri [1..*]
}
class "Dataset" as Dataset #EEEEEE
Dataset *-- "1" CatalogRecord : subjectOf
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
CatalogRecord ..> XsdAnyUri : conformsTo

@enduml