@startuml
title Instant
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "Instant" as Instant #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "TemporalExtent" as TemporalExtent #EEEEEE
TemporalExtent *-- "0..1" Instant : hasBeginning
TemporalExtent *-- "0..1" Instant : hasEnd
class "TimePosition" as TimePosition #EEEEEE
Instant *-- "0..1" TimePosition : inTimePosition
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
Instant ..> XsdAnyUri : identifier

@enduml