@startuml
title LabelForDisplay
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LabelForDisplay" as LabelForDisplay <<dataType>> #FAE5D3 {
  +locationVariant : ControlledVocabularyEntry [1]
  +maxLength : integer [1]
  +validDates : DateRange [1]
}
class "DescriptorValueDomain" as DescriptorValueDomain #EEEEEE
DescriptorValueDomain ..> LabelForDisplay : displayLabel
class "UnitType" as UnitType #EEEEEE
UnitType ..> LabelForDisplay : displayLabel

@enduml