@startuml
title Action
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam linetype ortho
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Action" as Action #FEFECE {
  +name : string [0..1]
}
class "WebAPI" as WebAPI #EEEEEE
WebAPI --> "0..*" Action : potentialAction
class "EntryPoint" as EntryPoint #EEEEEE
Action --> "1" EntryPoint : target
class "ActionResult" as ActionResult #EEEEEE
Action --> "0..1" ActionResult : result
class "PropertyValueSpecification" as PropertyValueSpecification #EEEEEE
Action --> "0..*" PropertyValueSpecification : queryInput

@enduml