@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdAnyUri : url
class "VariableMeasured" as VariableMeasured #EEEEEE
VariableMeasured ..> XsdAnyUri : propertyId
abstract class "AbstractGeometry" as AbstractGeometry #EEEEEE
AbstractGeometry ..> XsdAnyUri : crs
class "QualityMeasure" as QualityMeasure #EEEEEE
QualityMeasure ..> XsdAnyUri : metric
QualityMeasure ..> XsdAnyUri : unit
class "Concept" as Concept #EEEEEE
Concept ..> XsdAnyUri : inScheme
class "Identifier" as Identifier #EEEEEE
Identifier ..> XsdAnyUri : url
class "DefinedTerm" as DefinedTerm #EEEEEE
DefinedTerm ..> XsdAnyUri : identifier
DefinedTerm ..> XsdAnyUri : inDefinedTermSet
class "DataDownload" as DataDownload #EEEEEE
DataDownload ..> XsdAnyUri : contentUrl
DataDownload ..> XsdAnyUri : url
class "WebAPI" as WebAPI #EEEEEE
WebAPI ..> XsdAnyUri : url
class "Organization" as Organization #EEEEEE
Organization ..> XsdAnyUri : url
class "AdditionalProperty" as AdditionalProperty #EEEEEE
AdditionalProperty ..> XsdAnyUri : unitCode
class "Reference" as Reference #EEEEEE
Reference ..> XsdAnyUri : url
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo

@enduml