@startuml
title Address
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "Address" as Address <<dataType>> #FAE5D3 {
  +cityPlaceLocal : string [1]
  +countryCode : ControlledVocabularyEntry [1]
  +effectiveDates : DateRange [1]
  +geographicPoint : SpatialPoint [1]
  +isPreferred : boolean [1]
  +line : string [1..*]
  +locationName : ObjectName [1]
  +postalCode : string [1]
  +privacy : ControlledVocabularyEntry [1]
  +regionalCoverage : ControlledVocabularyEntry [1]
  +stateProvince : string [1]
  +timeZone : ControlledVocabularyEntry [1]
  +typeOfAddress : ControlledVocabularyEntry [1]
  +typeOfLocation : ControlledVocabularyEntry [1]
}

@enduml