@startuml
title AgentInRole
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "AgentInRole" as AgentInRole <<dataType>> #FAE5D3 {
  +agentName : BibliographicName [1]
  +reference : Reference [1]
  +role : PairedControlledVocabularyEntry [1..*]
}

@enduml