@startuml
title CatalogDetails
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "CatalogDetails" as CatalogDetails <<dataType>> #FAE5D3 {
  +access : AccessInformation [1..*]
  +alternativeTitle : InternationalString [1..*]
  +contributor : AgentInRole [1..*]
  +creator : AgentInRole [1..*]
  +date : CombinedDate [1..*]
  +identifier : InternationalIdentifier [1]
  +informationSource : InternationalString [1..*]
  +languageOfObject : XsdLanguage [1..*]
  +provenance : ProvenanceInformation [1]
  +publisher : AgentInRole [1..*]
  +relatedResource : Reference [1..*]
  +subTitle : InternationalString [1..*]
  +summary : InternationalString [1]
  +title : InternationalString [1]
  +typeOfResource : ControlledVocabularyEntry [1..*]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable ..> CatalogDetails : catalogDetails
class "DescriptorVariable" as DescriptorVariable #EEEEEE
DescriptorVariable ..> CatalogDetails : catalogDetails
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain ..> CatalogDetails : catalogDetails
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain ..> CatalogDetails : catalogDetails
class "DescriptorValueDomain" as DescriptorValueDomain #EEEEEE
DescriptorValueDomain ..> CatalogDetails : catalogDetails
class "UnitType" as UnitType #EEEEEE
UnitType ..> CatalogDetails : catalogDetails

@enduml