@startuml
title CategoryRelationCode
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

enum "CategoryRelationCode" as CategoryRelationCode <<enumeration>> #F9E79F
{
  Continuous
  Interval
  Nominal
  Ordinal
  Ratio
}
class "ValueAndConceptDescription" as ValueAndConceptDescription #EEEEEE
ValueAndConceptDescription ..> CategoryRelationCode : classificationLevel

@enduml