@startuml
title conformsTo
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "conformsTo" as conformsTo <<dataType>> #FAE5D3
class "PhysicalDataSet" as PhysicalDataSet #EEEEEE
PhysicalDataSet ..> conformsTo : standard
class "TabularTextDataSet" as TabularTextDataSet #EEEEEE
TabularTextDataSet ..> conformsTo : standard
class "StructuredDataSet" as StructuredDataSet #EEEEEE
StructuredDataSet ..> conformsTo : standard

@enduml