@startuml
title LabelForDisplay
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "LabelForDisplay" as LabelForDisplay <<dataType>> #FAE5D3 {
  +locationVariant : ControlledVocabularyEntry [1]
  +maxLength : integer [1]
  +validDates : DateRange [1]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable ..> LabelForDisplay : displayLabel
class "DescriptorVariable" as DescriptorVariable #EEEEEE
DescriptorVariable ..> LabelForDisplay : displayLabel
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain ..> LabelForDisplay : displayLabel
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain ..> LabelForDisplay : displayLabel
class "DescriptorValueDomain" as DescriptorValueDomain #EEEEEE
DescriptorValueDomain ..> LabelForDisplay : displayLabel
class "UnitType" as UnitType #EEEEEE
UnitType ..> LabelForDisplay : displayLabel

@enduml