@startuml
title LanguageString
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "LanguageString" as LanguageString <<dataType>> #FAE5D3 {
  +content : string [1]
  +isTranslatable : boolean [1]
  +isTranslated : boolean [1]
  +language : XsdLanguage [1]
  +scope : string [1]
  +structureUsed : ControlledVocabularyEntry [1]
  +translationDate : XsdDate [1]
  +translationSourceLanguage : XsdLanguage [1..*]
}

@enduml