@startuml
title ObjectName
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "ObjectName" as ObjectName <<dataType>> #FAE5D3 {
  +context : ControlledVocabularyEntry [1]
  +name : string [1]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable ..> ObjectName : name
class "DescriptorVariable" as DescriptorVariable #EEEEEE
DescriptorVariable ..> ObjectName : name
class "EnumerationDomain" as EnumerationDomain #EEEEEE
EnumerationDomain ..> ObjectName : name
class "UnitType" as UnitType #EEEEEE
UnitType ..> ObjectName : name

@enduml