@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "EnumerationDomain" as EnumerationDomain #EEEEEE
EnumerationDomain ..> XsdAnyUri : references
class "VariableMeasured" as VariableMeasured #EEEEEE
VariableMeasured ..> XsdAnyUri : propertyId
class "DataDownload" as DataDownload #EEEEEE
DataDownload ..> XsdAnyUri : contentUrl
DataDownload ..> XsdAnyUri : url
class "Concept" as Concept #EEEEEE
Concept ..> XsdAnyUri : inScheme
class "Identifier" as Identifier #EEEEEE
Identifier ..> XsdAnyUri : url
class "DefinedTerm" as DefinedTerm #EEEEEE
DefinedTerm ..> XsdAnyUri : identifier
DefinedTerm ..> XsdAnyUri : inDefinedTermSet
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdAnyUri : url
abstract class "AbstractGeometry" as AbstractGeometry #EEEEEE
AbstractGeometry ..> XsdAnyUri : crs
class "TemporalExtent" as TemporalExtent #EEEEEE
TemporalExtent ..> XsdAnyUri : intervalStartedBy
TemporalExtent ..> XsdAnyUri : intervalFinishedBy
class "Instant" as Instant #EEEEEE
Instant ..> XsdAnyUri : identifier
class "TimePosition" as TimePosition #EEEEEE
TimePosition ..> XsdAnyUri : hasTRS
class "Geometry" as Geometry #EEEEEE
Geometry ..> XsdAnyUri : crs
class "QualityMeasurement" as QualityMeasurement #EEEEEE
QualityMeasurement ..> XsdAnyUri : isMeasurementOf
QualityMeasurement ..> XsdAnyUri : unit
class "WebAPI" as WebAPI #EEEEEE
WebAPI ..> XsdAnyUri : url
class "Organization" as Organization #EEEEEE
Organization ..> XsdAnyUri : url
class "AdditionalProperty" as AdditionalProperty #EEEEEE
AdditionalProperty ..> XsdAnyUri : unitCode
class "Reference" as Reference #EEEEEE
Reference ..> XsdAnyUri : url
class "ProvActivity" as ProvActivity #EEEEEE
ProvActivity ..> XsdAnyUri : used
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo

@enduml