@startuml
title XsdAnyUri
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
class "DataDownload" as DataDownload #EEEEEE
DataDownload ..> XsdAnyUri : identifier
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdAnyUri : conformsTo
abstract class "DataStructureComponent" as DataStructureComponent #EEEEEE
DataStructureComponent ..> XsdAnyUri : identifier
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable ..> XsdAnyUri : identifier
abstract class "AbstractDataStructure" as AbstractDataStructure #EEEEEE
AbstractDataStructure ..> XsdAnyUri : identifier
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup ..> XsdAnyUri : identifier
class "PrimaryKey" as PrimaryKey #EEEEEE
PrimaryKey ..> XsdAnyUri : identifier
class "PrimaryKeyComponent" as PrimaryKeyComponent #EEEEEE
PrimaryKeyComponent ..> XsdAnyUri : identifier
class "ForeignKey" as ForeignKey #EEEEEE
ForeignKey ..> XsdAnyUri : identifier
class "ForeignKeyComponent" as ForeignKeyComponent #EEEEEE
ForeignKeyComponent ..> XsdAnyUri : identifier

@enduml