@startuml
title XsdDate
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "XsdDate" as XsdDate <<dataType>> #FAE5D3
class "DataDownload" as DataDownload #EEEEEE
DataDownload ..> XsdDate : dateModified
DataDownload ..> XsdDate : datePublished
class "Dataset" as Dataset #EEEEEE
Dataset ..> XsdDate : dateModified
Dataset ..> XsdDate : datePublished
class "TemporalExtent" as TemporalExtent #EEEEEE
TemporalExtent ..> XsdDate : startDate
TemporalExtent ..> XsdDate : endDate
class "Contributor" as Contributor #EEEEEE
Contributor ..> XsdDate : startDate
Contributor ..> XsdDate : endDate
class "ProvActivity" as ProvActivity #EEEEEE
ProvActivity ..> XsdDate : startedAtTime
ProvActivity ..> XsdDate : endedAtTime
class "CatalogRecord" as CatalogRecord #EEEEEE
CatalogRecord ..> XsdDate : dateCreated
CatalogRecord ..> XsdDate : dateModified
CatalogRecord ..> XsdDate : sdDatePublished

@enduml