@startuml
title CatalogRecord
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "CatalogRecord" as CatalogRecord #FEFECE {
  +identifier : Identifier [0..1]
  +conformsTo : XsdAnyUri [1..*]
  +dateCreated : XsdDate [0..1]
  +dateModified : XsdDate [0..1]
  +inLanguage : XsdLanguage [0..1]
  +sdDatePublished : XsdDate [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "1" CatalogRecord : subjectOf
CatalogRecord --> "0..1" Dataset : about
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
CatalogRecord ..> XsdAnyUri : conformsTo
class "XsdDate" as XsdDate <<dataType>> #FAE5D3
CatalogRecord ..> XsdDate : dateCreated
class "XsdLanguage" as XsdLanguage <<dataType>> #FAE5D3
CatalogRecord ..> XsdLanguage : inLanguage

@enduml