@startuml
title QuantitativeValue
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "QuantitativeValue" as QuantitativeValue #FEFECE {
  +value : number [1]
  +unitText : string [1]
}
class "ArchivePart" as ArchivePart #EEEEEE
ArchivePart *-- "0..1" QuantitativeValue : size

@enduml