@startuml
title AbstractDataStructureComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

abstract class "AbstractDataStructureComponent" as AbstractDataStructureComponent #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "IdentifierComponent" as IdentifierComponent #D5F5E3
AbstractDataStructureComponent <|-- IdentifierComponent
class "MeasureComponent" as MeasureComponent #D5F5E3
AbstractDataStructureComponent <|-- MeasureComponent
class "AttributeComponent" as AttributeComponent #D5F5E3
AbstractDataStructureComponent <|-- AttributeComponent
class "DimensionComponent" as DimensionComponent #D5F5E3
AbstractDataStructureComponent <|-- DimensionComponent
class "VariableDescriptorComponent" as VariableDescriptorComponent #D5F5E3
AbstractDataStructureComponent <|-- VariableDescriptorComponent
class "VariableValueComponent" as VariableValueComponent #D5F5E3
AbstractDataStructureComponent <|-- VariableValueComponent
abstract class "AbstractDataStructure" as AbstractDataStructure #EEEEEE
AbstractDataStructure *-- "1..*" AbstractDataStructureComponent : hasComponent
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "1..*" AbstractDataStructureComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "1..*" AbstractDataStructureComponent : hasComponent
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure *-- "1..*" AbstractDataStructureComponent : hasComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure *-- "1..*" AbstractDataStructureComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "1..*" AbstractDataStructureComponent : hasComponent
class "PrimaryKeyComponent" as PrimaryKeyComponent #EEEEEE
PrimaryKeyComponent --> "0..1" AbstractDataStructureComponent : correspondsTo
class "ForeignKeyComponent" as ForeignKeyComponent #EEEEEE
ForeignKeyComponent --> "0..1" AbstractDataStructureComponent : correspondsTo
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
AbstractDataStructureComponent ..> XsdAnyUri : identifier

@enduml