@startuml
title AttributeComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "AttributeComponent" as AttributeComponent #FEFECE {
  +identifier : Identifier [1]
  +semantic : Concept [1..*]
}
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- AttributeComponent
class "WideDataStructure" as WideDataStructure #EEEEEE
WideDataStructure --> "0..*" AttributeComponent : has
class "LongDataStructure" as LongDataStructure #EEEEEE
LongDataStructure --> "0..*" AttributeComponent : has
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure --> "0..*" AttributeComponent : has
class "RepresentedVariable" as RepresentedVariable #EEEEEE
AttributeComponent --> "1" RepresentedVariable : isDefinedBy
class "MeasureComponent" as MeasureComponent #EEEEEE
AttributeComponent --> "0..*" MeasureComponent : qualifies
class "Identifier" as Identifier #EEEEEE
AttributeComponent --> "1" Identifier : identifier
class "Concept" as Concept #EEEEEE
AttributeComponent --> "1..*" Concept : semantic

@enduml