@startuml
title ConceptSystem
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ConceptSystem" as ConceptSystem #FEFECE {
  +allowsDuplicates : boolean [1]
  +externalDefinition : Reference [1]
  +identifier : Identifier [1]
  +name : string [1..*]
  +purpose : string [1]
}
class "Concept" as Concept #EEEEEE
ConceptSystem --> "0..*" Concept : has
class "SubstantiveConceptualDomain" as SubstantiveConceptualDomain #EEEEEE
SubstantiveConceptualDomain --> "0..1" ConceptSystem : takesConceptsFrom
class "SentinelConceptualDomain" as SentinelConceptualDomain #EEEEEE
SentinelConceptualDomain --> "0..1" ConceptSystem : takesConceptsFrom
class "Reference" as Reference #EEEEEE
ConceptSystem --> "1" Reference : externalDefinition
class "Identifier" as Identifier #EEEEEE
ConceptSystem --> "1" Identifier : identifier

@enduml