@startuml
title ContactPoint
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ContactPoint" as ContactPoint #FEFECE {
  +email : string [1]
}

@enduml