@startuml
title DataDownload
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataDownload" as DataDownload #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "CatalogRecord" as CatalogRecord #EEEEEE
DataDownload --> "0..1" CatalogRecord : subjectOf
class "DataStructure" as DataStructure #EEEEEE
DataDownload --> "0..1" DataStructure : isStructuredBy
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DataDownload --> "0..1" DimensionalDataStructure : isStructuredBy
class "LongDataStructure" as LongDataStructure #EEEEEE
DataDownload --> "0..1" LongDataStructure : isStructuredBy
class "WideDataStructure" as WideDataStructure #EEEEEE
DataDownload --> "0..1" WideDataStructure : isStructuredBy
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DataDownload ..> XsdAnyUri : identifier

@enduml