@startuml
title DataDownload
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DataDownload" as DataDownload #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "CatalogRecord" as CatalogRecord #EEEEEE
DataDownload --> "0..1" CatalogRecord : subjectOf
abstract class "AbstractDataStructure" as AbstractDataStructure #EEEEEE
DataDownload --> "0..1" AbstractDataStructure : isStructuredBy
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DataDownload ..> XsdAnyUri : identifier

@enduml