@startuml
title DerivedFrom
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DerivedFrom" as DerivedFrom #FEFECE {
  +name : string [0..1]
  +description : string [0..1]
  +url : XsdAnyUri [0..1]
  +relation : XsdAnyUri [0..1]
  +hadRole : DefinedTerm [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" DerivedFrom : wasDerivedFrom
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
DerivedFrom ..> XsdAnyUri : url
class "DefinedTerm" as DefinedTerm #EEEEEE
DerivedFrom --> "0..1" DefinedTerm : hadRole

@enduml