@startuml
title DerivedFrom
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DerivedFrom" as DerivedFrom #FEFECE {
  +identifier : Identifier [1]
  +name : string [0..1]
}
class "Dataset" as Dataset #EEEEEE
Dataset --> "0..*" DerivedFrom : wasDerivedFrom

@enduml