@startuml
title DimensionGroup
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionGroup" as DimensionGroup #FEFECE {
  +type : String [1..*]
  +identifier : String [0..1]
  +name : String [1..*]
}

class "Identifier" as Identifier #D6EAF8

class "id-reference" as id-reference #FEFECE

DimensionGroup --> "0..1" Identifier : identifier
DimensionGroup --> "1..*" id-reference : has_DataStructureComponent
@enduml
