@startuml
title DimensionalDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionalDataStructure" as DimensionalDataStructure #FEFECE {
  +type : String [1..*]
  +identifier : String [0..1]
}

class "IdentifierComponent" as IdentifierComponent #D6EAF8

class "PrimaryKey" as PrimaryKey #FEFECE

DimensionalDataStructure --> "1..*" IdentifierComponent : has_DataStructureComponent
DimensionalDataStructure --> "0..1" PrimaryKey : has_PrimaryKey
@enduml
