@startuml
title DimensionalDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "DimensionalDataStructure" as DimensionalDataStructure #FEFECE
class "DataStructure" as DataStructure #D6EAF8
DataStructure <|-- DimensionalDataStructure
class "IdentifierComponent" as IdentifierComponent #EEEEEE
DimensionalDataStructure --> "0..*" IdentifierComponent : has
class "DimensionComponent" as DimensionComponent #EEEEEE
DimensionalDataStructure --> "1..*" DimensionComponent : has
class "MeasureComponent" as MeasureComponent #EEEEEE
DimensionalDataStructure --> "1..*" MeasureComponent : has
class "AttributeComponent" as AttributeComponent #EEEEEE
DimensionalDataStructure --> "0..*" AttributeComponent : has
class "ComponentPosition" as ComponentPosition #EEEEEE
DimensionalDataStructure --> "1..*" ComponentPosition : has

@enduml