@startuml
title DimensionComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam ranksep 250
skinparam nodesep 20
skinparam defaultFontSize 36
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 36
  AttributeFontSize 30
}

class "DimensionComponent" as DimensionComponent #FEFECE
abstract class "DataStructureComponent" as DataStructureComponent #D6EAF8
DataStructureComponent <|-- DimensionComponent
class "DataStructure" as DataStructure #EEEEEE
DataStructure *-- "0..*" DimensionComponent : hasComponent
class "DimensionalDataStructure" as DimensionalDataStructure #EEEEEE
DimensionalDataStructure *-- "1..*" DimensionComponent : hasComponent
class "DimensionGroup" as DimensionGroup #EEEEEE
DimensionGroup *-- "0..*" DimensionComponent : hasComponent

@enduml