@startuml
title ForeignKeyComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ForeignKeyComponent" as ForeignKeyComponent #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "ForeignKey" as ForeignKey #EEEEEE
ForeignKey *-- "1..*" ForeignKeyComponent : isComposedOf
class "PrimaryKeyComponent" as PrimaryKeyComponent #EEEEEE
ForeignKeyComponent --> "0..1" PrimaryKeyComponent : references
abstract class "AbstractDataStructureComponent" as AbstractDataStructureComponent #EEEEEE
ForeignKeyComponent --> "0..1" AbstractDataStructureComponent : correspondsTo
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
ForeignKeyComponent ..> XsdAnyUri : identifier

@enduml