@startuml
title ForeignKeyComponent
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ForeignKeyComponent" as ForeignKeyComponent #FEFECE {
  +identifier : Identifier [1]
}
class "ForeignKey" as ForeignKey #EEEEEE
ForeignKey --> "1..*" ForeignKeyComponent : isComposedOf
abstract class "DataStructureComponent" as DataStructureComponent #EEEEEE
ForeignKeyComponent --> "1" DataStructureComponent : correspondsTo
class "PrimaryKeyComponent" as PrimaryKeyComponent #EEEEEE
ForeignKeyComponent --> "1" PrimaryKeyComponent : references
class "Identifier" as Identifier #EEEEEE
ForeignKeyComponent --> "1" Identifier : identifier

@enduml