@startuml
title ForeignKey
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ForeignKey" as ForeignKey #FEFECE {
  +type : String [1..*]
  +identifier : String [0..1]
}

class "Identifier" as Identifier #D6EAF8

class "ForeignKeyComponent" as ForeignKeyComponent #FEFECE

ForeignKey --> "0..1" Identifier : identifier
ForeignKey --> "1..*" ForeignKeyComponent : isComposedOf
@enduml
