@startuml
title id-reference
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "id-reference" as id-reference #FEFECE {
  +identifier : String [1]
}

@enduml
