@startuml
title InstanceVariable
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "InstanceVariable" as InstanceVariable #FEFECE {
  +identifier : XsdAnyUri [0..1]
}
class "PrimaryKey" as PrimaryKey #EEEEEE
PrimaryKey --> "1..*" InstanceVariable : isComposedOf
class "XsdAnyUri" as XsdAnyUri <<dataType>> #FAE5D3
InstanceVariable ..> XsdAnyUri : identifier

@enduml