@startuml
title LongDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LongDataStructure" as LongDataStructure #FEFECE {
  +type : String [1..*]
  +identifier : String [0..1]
}

class "IdentifierComponent" as IdentifierComponent #D6EAF8

class "PrimaryKey" as PrimaryKey #FEFECE

LongDataStructure --> "3..*" IdentifierComponent : has_DataStructureComponent
LongDataStructure --> "0..1" PrimaryKey : has_PrimaryKey
@enduml
