@startuml
title LongDataStructure
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "LongDataStructure" as LongDataStructure #FEFECE {
  +identifier : Identifier [1]
  +semantic : Concept [1..*]
}
class "IdentifierComponent" as IdentifierComponent #EEEEEE
LongDataStructure --> "1..*" IdentifierComponent : has
class "VariableDescriptorComponent" as VariableDescriptorComponent #EEEEEE
LongDataStructure --> "1..*" VariableDescriptorComponent : has
class "VariableValueComponent" as VariableValueComponent #EEEEEE
LongDataStructure --> "1..*" VariableValueComponent : has
class "AttributeComponent" as AttributeComponent #EEEEEE
LongDataStructure --> "0..*" AttributeComponent : has

@enduml