@startuml
title PhysicalDataSet
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "PhysicalDataSet" as PhysicalDataSet #FEFECE {
  +characterSet : string [1]
  +encoding : Concept [1]
  +fileSize : number [1]
  +fileSizeUofM : string [1]
  +fingerprint : DataFingerprint [1]
  +identifier : Identifier [1]
  +name : string [1]
  +overview : string [1]
  +physicalFileURL : string [1]
  +purpose : string [1]
  +recordCount : integer [1]
  +standard : conformsTo [1..*]
}
class "DataStructure" as DataStructure #EEEEEE
PhysicalDataSet --> "0..1" DataStructure : isStructuredBy
class "Concept" as Concept #EEEEEE
PhysicalDataSet --> "1" Concept : encoding
class "DataFingerprint" as DataFingerprint <<dataType>> #FAE5D3
PhysicalDataSet ..> DataFingerprint : fingerprint
class "Identifier" as Identifier #EEEEEE
PhysicalDataSet --> "1" Identifier : identifier
class "conformsTo" as conformsTo <<dataType>> #FAE5D3
PhysicalDataSet ..> conformsTo : standard

@enduml