@startuml
title PrimaryKey
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "PrimaryKey" as PrimaryKey #FEFECE {
  +type : String [1..*]
  +identifier : String [0..1]
}

class "id-reference" as id-reference #FEFECE

PrimaryKey --> "1..*" id-reference : isComposedOf
@enduml
