@startuml
title RepresentedVariable
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "RepresentedVariable" as RepresentedVariable #FEFECE {
  +name : string [1]
  +definition : string [1]
}
abstract class "DataStructureComponent" as DataStructureComponent #EEEEEE
DataStructureComponent --> "1" RepresentedVariable : isDefinedBy
class "IdentifierComponent" as IdentifierComponent #EEEEEE
IdentifierComponent --> "1" RepresentedVariable : isDefinedBy
class "MeasureComponent" as MeasureComponent #EEEEEE
MeasureComponent --> "1" RepresentedVariable : isDefinedBy
class "AttributeComponent" as AttributeComponent #EEEEEE
AttributeComponent --> "1" RepresentedVariable : isDefinedBy
class "DimensionComponent" as DimensionComponent #EEEEEE
DimensionComponent --> "1" RepresentedVariable : isDefinedBy
class "VariableValueComponent" as VariableValueComponent #EEEEEE
VariableValueComponent --> "1" RepresentedVariable : isDefinedBy
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
RepresentedVariable --> "0..*" SubstantiveValueDomain : takesSubstantiveValuesFrom
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
RepresentedVariable --> "0..*" SentinelValueDomain : takesSentinelValuesFrom
class "UnitType" as UnitType #EEEEEE
RepresentedVariable --> "0..1" UnitType : measures
class "InstanceVariable" as InstanceVariable #EEEEEE
InstanceVariable --> "1" RepresentedVariable : uses

@enduml