@startuml
title SentinelValueDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "SentinelValueDomain" as SentinelValueDomain #FEFECE {
  +platformType : Concept [1]
  +displayLabel : string [1..*]
  +identifier : Identifier [1]
  +recommendedDataType : Concept [1..*]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable "0..*" <-- SentinelValueDomain : takesSentinelValuesFrom

@enduml