@startuml
title Statistic
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "Statistic" as Statistic #FEFECE {
  +computationBase : string [0..1]
  +content : number [0..1]
  +isWeighted : boolean [0..1]
  +typeOfNumericValue : string [0..1]
}

@enduml