@startuml
title SubstantiveConceptualDomain
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "SubstantiveConceptualDomain" as SubstantiveConceptualDomain #FEFECE {
  +displayLabel : string [1..*]
  +identifier : Identifier [1]
}
class "RepresentedVariable" as RepresentedVariable #EEEEEE
RepresentedVariable --> "0..1" SubstantiveConceptualDomain : takesSubstantiveConceptsFrom
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain --> "0..1" SubstantiveConceptualDomain : takesConceptsFrom
class "ConceptSystem" as ConceptSystem #EEEEEE
SubstantiveConceptualDomain --> "0..1" ConceptSystem : takesConceptsFrom

@enduml