@startuml
title ValueAndConceptDescription
hide circle
hide empty members
skinparam shadowing false
skinparam ArrowThickness 1.2
skinparam class {
  ArrowColor #404040
  BorderColor #404040
  FontSize 12
}

class "ValueAndConceptDescription" as ValueAndConceptDescription #FEFECE {
  +classificationLevel : CategoryRelationCode [1]
  +description : string [1]
  +formatPattern : Concept [1]
  +identifier : Identifier [1]
  +logicalExpression : Concept [1]
  +maximumValueExclusive : string [1]
  +maximumValueInclusive : string [1]
  +minimumValueExclusive : string [1]
  +minimumValueInclusive : string [1]
  +regularExpression : string [1]
}
class "SubstantiveValueDomain" as SubstantiveValueDomain #EEEEEE
SubstantiveValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
class "SentinelValueDomain" as SentinelValueDomain #EEEEEE
SentinelValueDomain --> "0..1" ValueAndConceptDescription : isDescribedBy
enum "CategoryRelationCode" as CategoryRelationCode <<enumeration>> #F9E79F
{
  Continuous
  Interval
  Nominal
  Ordinal
  Ratio
}
ValueAndConceptDescription ..> CategoryRelationCode : classificationLevel
class "Concept" as Concept #EEEEEE
ValueAndConceptDescription --> "1" Concept : formatPattern
class "Identifier" as Identifier #EEEEEE
ValueAndConceptDescription --> "1" Identifier : identifier
ValueAndConceptDescription --> "1" Concept : logicalExpression

@enduml